version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: meu-redis-compose
    ports:
      - "6379:6379"

  api:
    build: .
    image: apilivros_teste
    container_name: minha-api-fastapi
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
