version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: meu-redis-compose
    ports:
      - "6379:6379"

  api:
    image: apilivros_teste
    container_name: minha-api-fastapi
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - redis
